baseURL = '/'
languageCode = 'en-id'
title = 'Ignatha blogs'
theme = 'ignatha'

[taxonomies]
   series = "series"
   categories = "categories"
   tags = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "title"
    weight = 30

  [[related.indices]]
    name = "description"
    weight = 30

  [[related.indices]]
    name = "tags"
    weight = 30

  [[related.indices]]
    name = "date"
    weight = 10

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

    [markup.goldmark.renderer]
    unsafe= true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

[minify]
    minifyOutput = true

[minify.tdewolff.html]
  keepWhitespace = false